
TB := fifoScoreboards_tb

space :=
space +=

INSTANCES =
#                               TYPE      WIDTH  DEPTH  FLOPS_NOT_MEM   TOPOLOGY  FORCEKEEP_NENTRIES  FAST_NOT_SMALL  CDC
INSTANCES += $(subst $(space),,"fifoW1R1, 1,     8,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 2,     8,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 5,     8,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     8,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 1,     8,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 2,     8,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 5,     8,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     8,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     2,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     3,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     4,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     5,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     2,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     3,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     4,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     5,     1,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"fifoW1R1, 8,     8,     0,              0,        1,                  0,              0")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     8,     0,              0,        0,                  1,              0")
INSTANCES += $(subst $(space),,"cdcFifo,  1,     8,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  2,     8,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  5,     8,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     8,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  1,     8,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  2,     8,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  5,     8,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     8,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     2,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     3,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     4,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     5,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     2,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     3,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     4,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcFifo,  8,     5,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  8,     2,     0,              0,        0,                  0,              0")
INSTANCES += $(subst $(space),,"cdcData,  8,     2,     0,              1,        0,                  0,              0")
INSTANCES += $(subst $(space),,"cdcData,  1,     2,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  2,     2,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  5,     2,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  8,     2,     0,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  1,     2,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  2,     2,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  5,     2,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  8,     2,     1,              0,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  1,     2,     0,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  2,     2,     0,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  5,     2,     0,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  8,     2,     0,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  1,     2,     1,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  2,     2,     1,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  5,     2,     1,              1,        0,                  0,              1")
INSTANCES += $(subst $(space),,"cdcData,  8,     2,     1,              1,        0,                  0,              1")
foo:
	echo $(INSTANCES)

N_CYCLES ?= 1000000

V_SRC := \
	$(TB).sv \
	../../hdl/cdcData.sv \
	../../hdl/cdcFifo.sv \
	../../hdl/fifoW1R1.sv

CC_SRC := \
	../../verif/modelPrint.cc \
	$(TB).cc

CC_H := \
	../../verif/modelPrint.h

CC_SRC ?= $(TB).cc

V_INCDIRS := ../../hdl ../../verif
VERILATOR_INCDIRS := $(addprefix -I,$(V_INCDIRS))

# Verilator compile verilog into C++.
VERILATOR_TOP ?= $(TB)
VERILATOR_TRACE_DEPTH ?= 3
$(BUILD)/V$(TB).mk: $(V_SRC) $(CC_SRC) $(CC_H)
	mkdir -p $(BUILD)
	verilator --cc \
		--trace \
		--trace-depth $(VERILATOR_TRACE_DEPTH) \
		--exe \
		$(VERILATOR_INCDIRS) \
		--Mdir $(BUILD) \
		-DN_CYCLES=$(N_CYCLES) \
		-CFLAGS -DN_CYCLES=$(N_CYCLES) \
		-CFLAGS -I../../../verif \
		$(VERILATOR_DPI_OBJS) \
		--clk common_clk \
		--top-module $(VERILATOR_TOP) \
		$(CC_SRC) \
		$(VERILATOR_TOP).sv

# Compile verilated C++ into executable.
$(BUILD)/V$(TB): $(BUILD)/V$(TB).mk $(VERILATOR_DPI_DEPS)
	make -j -C $(BUILD) -f V$(TB).mk V$(TB)

# Execute verilator object to dump VCD.
$(VCD_VERILATOR): $(BUILD)/V$(TB)
	time $(BUILD)/V$(TB) > $(BUILD)/$(TB).verilator.log
	@! grep -q ERROR $(BUILD)/$(TB).verilator.log

.PHONY: clean
clean:
	rm -rf $(BUILD)

.SECONDARY:
