
TB := logdropWindow_tb

V_SRC := \
	../../hdl/fxcs.v \
	../../hdl/onehotIdx.v \
	../../hdl/logdropWindow.v \
	$(TB).v

# NOTE: Verilator only - no support for Icarus yet.
VCD_IVERILOG :=

include ../common.mk
